<div class="juzaweb__topbar"> <?php
        global $jw_user;
    ?><div class="mr-3"><a href="<?php echo e(url('/')); ?>" class="mr-2" target="_blank" title="<?php echo e(trans('cms::app.view_site')); ?>"><i class="dropdown-toggle-icon fa fa-home" data-toggle="tooltip" data-placement="bottom" data-original-title="Visit website"></i> <?php echo e(trans('cms::app.view_site')); ?> </a></div><div class="mr-3"><div class="dropdown mr-4 d-none d-sm-block"><a href="javascript:void(0)" class="dropdown-toggle text-nowrap" data-toggle="dropdown"><i class="fa fa-plus"></i> <span class="dropdown-toggle-text"><?php echo e(trans('cms::app.new')); ?></span></a><div class="dropdown-menu" role="menu"><a class="dropdown-item" href="<?php echo e(route('admin.posts.create', ['posts'])); ?>"><?php echo e(trans('cms::app.post')); ?></a> <a class="dropdown-item" href="<?php echo e(route('admin.posts.create', ['pages'])); ?>"><?php echo e(trans('cms::app.page')); ?></a> <a class="dropdown-item" href="<?php echo e(route('admin.users.create')); ?>"><?php echo e(trans('cms::app.user')); ?></a></div></div></div> <?php app(\Juzaweb\CMS\Contracts\EventyContract::class)->action('backend.menu_top'); ?><div class="mr-auto"></div> <?php
        $langs = \Illuminate\Support\Facades\Cache::remember(
            'top_menu_languages',
            3600,
            function () {
                return app(\Juzaweb\CMS\Support\Manager\TranslationManager::class)->locale('cms')
                    ->languages();
            }
        );

        $current = $jw_user->language ?? get_config('language', 'en');
    ?><div class="dropdown mr-4 d-none d-sm-block"><a href="javascript:void(0)" class="dropdown-toggle text-nowrap" data-toggle="dropdown" data-offset="5,15" aria-expanded="false" ><span class="dropdown-toggle-text text-uppercase"><?php echo e($current); ?></span></a><div class="dropdown-menu dropdown-menu-right" role="menu"> <?php $__currentLoopData = $langs; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $lang): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?> <?php if($current == $lang['code']): ?> <?php continue; ?> <?php endif; ?> <a class="dropdown-item " href="<?php echo e(url()->current()); ?>?hl=<?php echo e($lang['code']); ?>"><span class="text-uppercase font-size-12 mr-1"><?php echo e($lang['code']); ?></span> <?php echo e($lang['name']); ?></a> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div> <?php
        $total = count_unread_notifications();

        $items = Auth::user()
            ->unreadNotifications()
            ->cacheFor(3600)
            ->orderBy('id', 'DESC')
            ->limit(5)
            ->get(['id', 'data', 'created_at']);
    ?><div class="juzaweb__topbar__notify dropdown mr-4 d-none d-sm-block"><a href="javascript:void(0)" class="dropdown-toggle text-nowrap" data-toggle="dropdown" aria-expanded="false" data-offset="0,15"><i class="dropdown-toggle-icon fa fa-bell-o"></i><span><?php echo e($total); ?></span></a><div class="juzaweb__topbar__actionsDropdownMenu dropdown-menu dropdown-menu-right" role="menu"><div style="width: 350px;"><div class="card-body"><div class="tab-content"><div class="jw__l1"><div class="text-uppercase mb-2 text-gray-6 mb-2 font-weight-bold"><?php echo e(trans('cms::app.notifications')); ?> (<?php echo e($total); ?>)</div><hr><ul class="list-unstyled"> <?php if($items->isEmpty()): ?><p><?php echo e(trans('cms::app.no_notifications')); ?></p> <?php else: ?> <?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $notify): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><li class="jw__l8__item"><a href="<?php echo e(route('admin.profile.notification', [$notify->id])); ?>" class="jw__l8__itemLink" data-turbolinks="false"><div class="jw__l8__itemPic bg-success"> <?php if(empty($notify->data['image'])): ?> <i class="fa fa-envelope-square"></i> <?php else: ?> <img src="<?php echo e(upload_url($notify->data['image'])); ?>" alt=""> <?php endif; ?></div><div><div class="text-blue"><?php echo e($notify->data['subject'] ?? ''); ?></div><div class="text-muted"><?php echo e($notify->created_at?->diffForHumans()); ?></div></div></a></li> <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?> <?php endif; ?></ul></div></div></div></div></div></div><div class="dropdown"><a href="" class="dropdown-toggle text-nowrap" data-toggle="dropdown" aria-expanded="false" data-offset="5,15"><img class="dropdown-toggle-avatar" src="<?php echo e($jw_user->getAvatar()); ?>" alt="User avatar" width="30" height="30"/> </a><div class="dropdown-menu dropdown-menu-right" role="menu"><a class="dropdown-item" href="<?php echo e(route('admin.profile')); ?>"><i class="dropdown-icon fa fa-user"></i> <?php echo e(trans('cms::app.profile')); ?> </a><div class="dropdown-divider"></div><a href="javascript:void(0)" data-turbolinks="false" class="dropdown-item auth-logout"><i class="dropdown-icon fa fa-sign-out"></i> <?php echo e(trans('cms::app.logout')); ?> </a></div></div></div><?php /**PATH E:\Laragon\cms\modules\Backend\Providers/../resources/views/backend/menu_top.blade.php ENDPATH**/ ?>